#!/usr/bin/env python3
"""
txt.py
-------------------
Text formatting and metrics utilities for 750words export processing.

Provides functions for text formatting, ordinal number conversion, paragraph
reflowing, and word count metrics. Designed for txt2md workflow processing
of 750words.com text exports.

Functions:
    ordinal: Convert day of month to ordinal string (1st, 2nd, 3rd, etc.)
    format_body: Format raw text lines with soft-break detection
    reflow_paragraph: Wrap paragraph lines to specified width
    compute_metrics: Calculate word count and reading time

Constants:
    ENTRY_MARKERS: Valid entry separator markers in 750words exports

Usage:
    from dev.utils.txt import ordinal, format_body, compute_metrics

    # Format ordinal dates
    day_str = ordinal(22)  # "22nd"

    # Format text body
    formatted = format_body(raw_lines)

    # Get word count and reading time
    wc, rt = compute_metrics(text_lines)
"""
# --- Annotations ---
from __future__ import annotations

# --- Standard library imports ---
from textwrap import TextWrapper
from typing import List, Tuple

# --- Third party imports ---
from textstat import lexicon_count  # type: ignore


# --- Entry Processing Constants ---
ENTRY_MARKERS = {"------ ENTRY ------", "===== ENTRY ====="}
"""
Valid entry separator markers used in 750words text exports.

These markers delimit individual journal entries in both:
- Raw text exports (processed by txt_entry.py)
- Formatted text output (generated by txtbuilder.py)
"""


# --- Ordinal dates ---
def ordinal(n: int) -> str:
    """
    Convert day of month to ordinal string.

    Handles English ordinal rules for day numbers.

    Args:
        n: Integer day of month (1-31)

    Returns:
        Number with ordinal suffix ("st", "nd", "rd", "th")

    Examples:
        >>> ordinal(1)
        '1st'
        >>> ordinal(22)
        '22nd'
        >>> ordinal(13)
        '13th'
    """
    if 10 <= n % 100 <= 20:
        return f"{n}th"
    if n % 10 == 1:
        return f"{n}st"
    if n % 10 == 2:
        return f"{n}nd"
    if n % 10 == 3:
        return f"{n}rd"
    return f"{n}th"


# --- Format body of text ---
def format_body(lines: List[str]) -> List[Tuple[str, bool]]:
    """
    Format raw body lines for Markdown processing.

    Processes each line to detect soft breaks (lines ending with backslash),
    strip whitespace, and preserve blank lines for paragraph separation.

    Args:
        lines: List of raw body lines (strings) from text document

    Returns:
        List of (line_text, is_soft_break) tuples where:
        - line_text: Line with leading/trailing whitespace stripped
        - is_soft_break: True if line ends with backslash (Markdown soft break)
        - Blank lines are preserved for paragraph separation

    Processing:
        - Strips newline characters from each line
        - Detects backslash endings for Markdown soft breaks
        - Trims whitespace while preserving soft-break markers
        - Collapses consecutive blank lines into single blank line
    """
    out: List[Tuple[str, bool]] = []
    prev_blank: bool = False

    for raw in lines:
        ln: str = raw.rstrip("\n")

        # soft-break marker (single backslash)
        soft_break: bool = ln.rstrip().endswith("\\")
        if soft_break:
            ln = ln.rstrip()  # Keep the backslash for Markdown

        # trim whitespace
        ln = ln.strip()

        # blank line
        if ln == "":
            if not prev_blank:
                out.append(("", False))
                prev_blank = True
        else:
            out.append((ln, soft_break))
            prev_blank = False
    return out


# --- Wrap entry -> <80 chars ---
def reflow_paragraph(paragraph: List[str], width: int = 80) -> List[str]:
    """
    Wrap paragraph lines to specified character width.

    Joins paragraph lines with spaces and applies text wrapping using
    Python's textwrap module to ensure lines don't exceed the width limit.

    Args:
        paragraph: List of lines (strings) without blank lines
        width: Maximum character width per line (default: 80)

    Returns:
        List of wrapped lines, each at most `width` characters long

    Examples:
        >>> reflow_paragraph(["This is a very long line that needs wrapping"], 20)
        ['This is a very long', 'line that needs', 'wrapping']
    """
    text: str = " ".join(paragraph)
    wrapper = TextWrapper(
        width=width,
        replace_whitespace=False,
        drop_whitespace=True,
    )
    return wrapper.wrap(text)


# --- Word-count & ~reading time ---
def compute_metrics(lines: List[str]) -> Tuple[int, float]:
    """
    Compute word count and reading time metrics for text.

    Calculates the number of words (excluding punctuation) and estimates
    reading time based on 260 words per minute average reading speed.

    Args:
        lines: List of text lines comprising the complete entry

    Returns:
        Tuple of (word_count, reading_time_min) where:
        - word_count: Number of words (excluding punctuation)
        - reading_time_min: Estimated reading time in minutes (260 WPM)

    Examples:
        >>> compute_metrics(["Hello world", "This is a test"])
        (6, 0.023)
    """
    text = " ".join(line.strip() for line in lines)
    wc: int = lexicon_count(text, removepunct=True)
    # texstat.reading_time gives inflated result.
    # Calculate manually with 260 WPM
    rt: float = wc / 260
    return (wc, rt)
