"""Add notes field to Event model

Revision ID: 7e66aaf42c1e
Revises: f060de8a49a9
Create Date: 2025-11-13 04:39:45.825317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e66aaf42c1e'
down_revision: Union[str, Sequence[str], None] = 'f060de8a49a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notes')
    # ### end Alembic commands ###
