"""Add manuscript entry and character fields

Revision ID: d27932f4e887
Revises: 7e66aaf42c1e
Create Date: 2025-11-13 05:22:38.174678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27932f4e887'
down_revision: Union[str, Sequence[str], None] = '7e66aaf42c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuscript_entries', sa.Column('entry_type', sa.Enum('vignette', 'scene', 'summary', 'reflection', 'dialogue', name='entrytype'), nullable=True))
    op.add_column('manuscript_entries', sa.Column('character_notes', sa.Text(), nullable=True))
    op.add_column('manuscript_entries', sa.Column('narrative_arc', sa.String(), nullable=True))
    op.create_index(op.f('ix_manuscript_entries_entry_type'), 'manuscript_entries', ['entry_type'], unique=False)
    op.add_column('manuscript_people', sa.Column('character_description', sa.Text(), nullable=True))
    op.add_column('manuscript_people', sa.Column('character_arc', sa.Text(), nullable=True))
    op.add_column('manuscript_people', sa.Column('voice_notes', sa.Text(), nullable=True))
    op.add_column('manuscript_people', sa.Column('appearance_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manuscript_people', 'appearance_notes')
    op.drop_column('manuscript_people', 'voice_notes')
    op.drop_column('manuscript_people', 'character_arc')
    op.drop_column('manuscript_people', 'character_description')
    op.drop_index(op.f('ix_manuscript_entries_entry_type'), table_name='manuscript_entries')
    op.drop_column('manuscript_entries', 'narrative_arc')
    op.drop_column('manuscript_entries', 'character_notes')
    op.drop_column('manuscript_entries', 'entry_type')
    # ### end Alembic commands ###
